### ISSUE TITLE
React Native 0.40

### ISSUE THREAD

**Issue by jacobp100** [callstack-io/react-native-snapshot-tests#1]
I’m trying to set this up in RN 0.40. I’ve created a PR (#2) that is the project based on RN 0.40, but I get the error attached. Have you had experience with this issue, and if so, did you have a fix?

Thanks!

![screen shot 2017-01-19 at 12 58 09](https://cloud.githubusercontent.com/assets/7275322/22107662/069872ea-de47-11e6-8bb1-b903295d6da2.png)

**Comment by tomauty** [comment]
I get this as well...anything I can do?
